wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.9.12
    cli_version: 0.17.8
    framework: huggingface
    huggingface_version: 4.44.0
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1732104146
    t:
      1:
      - 1
      - 11
      - 41
      - 49
      - 55
      - 71
      - 79
      - 83
      3:
      - 23
      4: 3.9.12
      5: 0.17.8
      6: 4.44.0
      8:
      - 5
      13: linux-x86_64
